spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog
          uri: http://localhost:8090
          predicates:
            - Path=/product/**, /category/**
          filters:
            - AuthFilter

        - id: report
          uri: http://localhost:8091
          predicates:
            - Path=/productReport/**
          filters:
            - AuthFilter

        - id: auth
          uri: http://localhost:8092
          predicates:
            - Path=/verif/**

eureka:
  client:
    register-with-eureka: true

server:
  port: 8080